import { pool } from '../config/database';
import type { RowDataPacket } from 'mysql2';
import { HttpError } from '../utils/http-error';
import { toPublicUser } from './auth.service';
type UserRow=RowDataPacket & {id:string;username:string;name:string;password_hash:string;role:'USER'|'ADMIN';is_active:number;country:string;city:string;gender:string;profile_image_url:string|null;is_verified:number;last_seen:Date|null;created_at:Date};
export async function getMe(id:string){const [rows]=await pool.execute<UserRow[]>('SELECT * FROM users WHERE id=? AND is_active=1',[id]);if(!rows[0])throw new HttpError(404,'USER_NOT_FOUND','User not found');return toPublicUser(rows[0]);}
export async function updateMe(id:string,data:{name?:string;country?:string;city?:string;gender?:string}){const columns:{[K in keyof typeof data]:string}={name:'name',country:'country',city:'city',gender:'gender'};const sets:string[]=[];const values:Array<string|null>=[];for(const key of Object.keys(data) as Array<keyof typeof data>){sets.push(`${columns[key]}=?`);values.push(data[key]??null);}values.push(id);const [result]=await pool.execute('UPDATE users SET '+sets.join(',')+' WHERE id=? AND is_active=1',values);if(!('affectedRows'in result)||result.affectedRows===0)throw new HttpError(404,'USER_NOT_FOUND','User not found');return getMe(id);}
export async function deactivateMe(id:string){const conn=await pool.getConnection();try{await conn.beginTransaction();const [r]=await conn.execute('UPDATE users SET is_active=0,updated_at=CURRENT_TIMESTAMP(3) WHERE id=? AND is_active=1',[id]);if(!('affectedRows'in r)||r.affectedRows===0)throw new HttpError(404,'USER_NOT_FOUND','User not found');await conn.execute('UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP(3) WHERE user_id=? AND revoked_at IS NULL',[id]);await conn.execute('UPDATE refresh_tokens rt JOIN sessions s ON s.id=rt.session_id SET rt.revoked_at=CURRENT_TIMESTAMP(3) WHERE s.user_id=? AND rt.revoked_at IS NULL',[id]);await conn.commit();}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
export async function listUsers(q:{search?:string;country?:string;city?:string;gender?:string;page:number;limit:number}){const where=['is_active=1'];const args:Array<string|number>=[];if(q.search){where.push('(username LIKE ? OR name LIKE ?)');args.push(`%${q.search}%`,`%${q.search}%`);}for(const [key,col] of [['country','country'],['city','city'],['gender','gender']] as const){const val=q[key];if(val){where.push(`${col}=?`);args.push(val);}}const clause=where.join(' AND ');const [count]=await pool.execute<(RowDataPacket & {total:number})[]>(`SELECT COUNT(*) AS total FROM users WHERE ${clause}`,args);const [rows]=await pool.execute<UserRow[]>(`SELECT * FROM users WHERE ${clause} ORDER BY created_at DESC LIMIT ? OFFSET ?`,[...args,q.limit,(q.page-1)*q.limit]);return {users:rows.map(toPublicUser),pagination:{page:q.page,limit:q.limit,total:Number(count[0]?.total??0),pages:Math.ceil(Number(count[0]?.total??0)/q.limit)}};}
