import { pool } from '../config/database';
import type { RowDataPacket } from 'mysql2';
import { HttpError } from '../utils/http-error';
import { toPublicUser } from './auth.service';
import type { PublicUserDto } from '../types/user.dto';
import { onlineStatusExpression, onlineStatusPredicate } from './online-status';
import { hasBlockBetween,notBlockedBetweenSql } from './blocks-check.service';
type UserRow=RowDataPacket & {id:string;username:string;name:string;password_hash:string;role:'USER'|'ADMIN';is_active:number;country:string;city:string;gender:string;profile_image_url:string|null;is_verified:number;last_seen:Date|null;created_at:Date};
export async function getMe(id:string){const [rows]=await pool.execute<UserRow[]>('SELECT * FROM users WHERE id=? AND is_active=1',[id]);if(!rows[0])throw new HttpError(404,'USER_NOT_FOUND','User not found');return toPublicUser(rows[0]);}
export async function updateMe(id:string,data:{name?:string;country?:string;city?:string;gender?:string}){const columns:{[K in keyof typeof data]:string}={name:'name',country:'country',city:'city',gender:'gender'};const sets:string[]=[];const values:Array<string|null>=[];for(const key of Object.keys(data) as Array<keyof typeof data>){sets.push(`${columns[key]}=?`);values.push(data[key]??null);}values.push(id);const [result]=await pool.execute('UPDATE users SET '+sets.join(',')+' WHERE id=? AND is_active=1',values);if(!('affectedRows'in result)||result.affectedRows===0)throw new HttpError(404,'USER_NOT_FOUND','User not found');return getMe(id);}
export async function deactivateMe(id:string){const conn=await pool.getConnection();try{await conn.beginTransaction();const [r]=await conn.execute('UPDATE users SET is_active=0,updated_at=CURRENT_TIMESTAMP(3) WHERE id=? AND is_active=1',[id]);if(!('affectedRows'in r)||r.affectedRows===0)throw new HttpError(404,'USER_NOT_FOUND','User not found');await conn.execute('UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP(3) WHERE user_id=? AND revoked_at IS NULL',[id]);await conn.execute('UPDATE refresh_tokens rt JOIN sessions s ON s.id=rt.session_id SET rt.revoked_at=CURRENT_TIMESTAMP(3) WHERE s.user_id=? AND rt.revoked_at IS NULL',[id]);await conn.commit();}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
type DirectoryRow=RowDataPacket & Omit<PublicUserDto,'profileImageUrl'|'isVerified'|'isOnline'|'lastSeen'> & {profile_image_url:string|null;is_verified:number;last_seen:Date|null;is_online:number};
function toDirectoryDto(row:DirectoryRow):PublicUserDto{return {id:row.id,username:row.username,name:row.name,country:row.country,city:row.city,gender:row.gender,profileImageUrl:row.profile_image_url,isVerified:Boolean(row.is_verified),isOnline:Boolean(row.is_online),lastSeen:row.last_seen};}
export async function getPublicProfile(id:string,viewerId?:string):Promise<PublicUserDto>{if(viewerId&&await hasBlockBetween(viewerId,id))throw new HttpError(404,'USER_NOT_FOUND','User not found');const [rows]=await pool.execute<DirectoryRow[]>(`SELECT id,username,name,country,city,gender,profile_image_url,is_verified,last_seen,${onlineStatusExpression('last_seen')} AS is_online FROM users WHERE id=? AND is_active=1`,[id]);if(!rows[0])throw new HttpError(404,'USER_NOT_FOUND','User not found');return toDirectoryDto(rows[0]);}
export async function listUsers(currentUserId:string,q:{search?:string;country?:string;city?:string;gender?:string;online?:boolean;page:number;limit:number}){const where=['is_active=1','id<>?',notBlockedBetweenSql('id','?')];const args:Array<string|number>=[currentUserId,currentUserId,currentUserId];if(q.search){const search=q.search.replace(/[!%_]/g,c=>`!${c}`);where.push("(username LIKE ? ESCAPE '!' OR name LIKE ? ESCAPE '!')");args.push(`${search}%`,`${search}%`);}for(const [key,col] of [['country','country'],['city','city'],['gender','gender']] as const){const val=q[key];if(val){where.push(`${col}=?`);args.push(val);}}if(q.online!==undefined)where.push(onlineStatusPredicate('last_seen',q.online));const clause=where.join(' AND ');const [count]=await pool.execute<(RowDataPacket & {total:number})[]>(`SELECT COUNT(*) AS total FROM users WHERE ${clause}`,args);const order=onlineStatusExpression('last_seen');const [rows]=await pool.execute<DirectoryRow[]>(`SELECT id,username,name,country,city,gender,profile_image_url,is_verified,last_seen,${order} AS is_online FROM users WHERE ${clause} ORDER BY ${order} DESC,last_seen DESC,username ASC,id ASC LIMIT ? OFFSET ?`,[...args,q.limit,(q.page-1)*q.limit]);const total=Number(count[0]?.total??0);return {users:rows.map(toDirectoryDto),pagination:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}};}
