import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { createServer, type Server as HttpServer } from 'node:http';
import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { io as clientIo, type Socket as ClientSocket } from 'socket.io-client';
import { app } from '../src/app';
import { pool } from '../src/config/database';
import sharp from 'sharp';
import { storageService } from '../src/storage/storage-service';
import { attachSocketServer } from '../src/realtime/socket-server';
import type { Ack, ClientToServerEvents, MessageDto, ServerToClientEvents } from '../src/types/messaging.dto';
import type { Server as SocketServer } from 'socket.io';

const enabled=process.env.RUN_MYSQL_INTEGRATION==='true';
const suffix=randomUUID().replaceAll('-','').slice(0,12);
const users=[
 {username:`chat_${suffix}_a`,name:'Chat Alice'},
 {username:`chat_${suffix}_b`,name:'Chat Bob'},
 {username:`chat_${suffix}_c`,name:'Chat Eve'}
].map(user=>({...user,password:'safe-test-password-123',confirmPassword:'safe-test-password-123',country:'Test',city:'Test',gender:'Other'}));
type TestSocket=ClientSocket<ServerToClientEvents,ClientToServerEvents>;
let ids:string[]=[];
let tokens:string[]=[];
let conversationId='';
let firstMessageId='';
let socketMessageId='';
let httpServer:HttpServer|undefined;
let ioServer:SocketServer<ClientToServerEvents,ServerToClientEvents>|undefined;
let sockets:TestSocket[]=[];
let baseUrl='';
function emitAck<T>(socket:TestSocket,event:string,payload:unknown):Promise<Ack<T>>{return new Promise(resolve=>{const emit=socket.emit as unknown as (event:string,payload:unknown,callback:(result:Ack<T>)=>void)=>void;emit.call(socket,event,payload,resolve);});}
async function connectSocket(token?:string):Promise<TestSocket>{return new Promise((resolve,reject)=>{const socket=clientIo(baseUrl,{auth:token?{token}:undefined,transports:['websocket'],reconnection:false,timeout:3000}) as TestSocket;socket.once('connect',()=>{sockets.push(socket);resolve(socket);});socket.once('connect_error',error=>{socket.close();reject(error);});});}
function waitForMessage(socket:TestSocket):Promise<MessageDto>{return new Promise(resolve=>socket.once('message:new',resolve));}
function waitForPresence(socket:TestSocket,userId:string,isOnline:boolean):Promise<{userId:string;isOnline:boolean;lastSeen:Date|null}>{return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{socket.off('presence:update',listener);reject(new Error(`Timed out waiting for ${userId} presence`));},3000);const listener=(value:{userId:string;isOnline:boolean;lastSeen:Date|null})=>{if(value.userId!==userId||value.isOnline!==isOnline)return;clearTimeout(timer);socket.off('presence:update',listener);resolve(value);};socket.on('presence:update',listener);});}

describe('MySQL and Socket.IO messaging flows',{skip:!enabled},()=>{
 before(async()=>{
  for(const user of users){const result=await request(app).post('/api/auth/register').send(user);assert.equal(result.status,201);ids.push(result.body.data.user.id);tokens.push(result.body.data.accessToken);}
  httpServer=createServer(app);ioServer=attachSocketServer(httpServer);
  await new Promise<void>(resolve=>httpServer!.listen(0,'127.0.0.1',resolve));
  const address=httpServer.address();if(!address||typeof address==='string')throw new Error('Test server address unavailable');baseUrl=`http://127.0.0.1:${address.port}`;
  sockets.push(await connectSocket(tokens[0]));sockets.push(await connectSocket(tokens[1]));sockets.push(await connectSocket(tokens[2]));
 });
 after(async()=>{
  for(const socket of sockets)socket.close();
  if(ioServer)await new Promise<void>(resolve=>ioServer!.close(()=>resolve()));
  if(ids.length){const[uploads]=await pool.execute<(import('mysql2').RowDataPacket&{storage_key:string})[]>('SELECT storage_key FROM uploads WHERE uploaded_by IN (?,?,?)',ids);await Promise.all(uploads.map(upload=>storageService.delete(upload.storage_key).catch(()=>undefined)));}
  for(const id of ids)await pool.execute('DELETE FROM users WHERE id=?',[id]);
  await pool.end();
 });

 it('creates a one-to-one conversation',async()=>{const result=await request(app).post('/api/conversations').set('Authorization',`Bearer ${tokens[0]}`).send({userId:ids[1]});assert.equal(result.status,201);conversationId=result.body.data.conversationId;assert.ok(conversationId);const owner=await emitAck<{conversationId:string}>(sockets[0]!,'conversation:join',{conversationId});const peer=await emitAck<{conversationId:string}>(sockets[1]!,'conversation:join',{conversationId});assert.equal(owner.success,true);assert.equal(peer.success,true);});
 it('returns the existing canonical conversation instead of duplicating it',async()=>{const result=await request(app).post('/api/conversations').set('Authorization',`Bearer ${tokens[1]}`).send({userId:ids[0]});assert.equal(result.status,201);assert.equal(result.body.data.conversationId,conversationId);const[count]=await pool.execute<(import('mysql2').RowDataPacket&{total:number})[]>('SELECT COUNT(*) AS total FROM conversations WHERE id=?',[conversationId]);assert.equal(Number(count[0]?.total),1);});
 it('rejects self-conversations',async()=>{const result=await request(app).post('/api/conversations').set('Authorization',`Bearer ${tokens[0]}`).send({userId:ids[0]});assert.equal(result.status,400);});
 it('lists only the authenticated user conversations',async()=>{const result=await request(app).get('/api/conversations').set('Authorization',`Bearer ${tokens[0]}`);assert.equal(result.status,200);assert.ok(result.body.data.some((item:{conversationId:string})=>item.conversationId===conversationId));});
 it('authorizes conversation details and hides non-member conversations',async()=>{const member=await request(app).get(`/api/conversations/${conversationId}`).set('Authorization',`Bearer ${tokens[1]}`);const outsider=await request(app).get(`/api/conversations/${conversationId}`).set('Authorization',`Bearer ${tokens[2]}`);assert.equal(member.status,200);assert.equal(outsider.status,404);});
 it('persists a valid text message before making it available',async()=>{const delivered=waitForMessage(sockets[1]!);const result=await request(app).post(`/api/conversations/${conversationId}/messages`).set('Authorization',`Bearer ${tokens[0]}`).send({content:'hello from REST'});assert.equal(result.status,201);assert.equal(result.body.data.status,'SENT');firstMessageId=result.body.data.id;const event=await delivered;assert.equal(event.id,firstMessageId);assert.equal(event.content,result.body.data.content);assert.equal(event.messageType,result.body.data.messageType);assert.equal(event.senderId,result.body.data.senderId);assert.equal(event.status,result.body.data.status);});
 it('rejects empty and overlong message content',async()=>{const empty=await request(app).post(`/api/conversations/${conversationId}/messages`).set('Authorization',`Bearer ${tokens[0]}`).send({content:'   '});const long=await request(app).post(`/api/conversations/${conversationId}/messages`).set('Authorization',`Bearer ${tokens[0]}`).send({content:'x'.repeat(4001)});assert.equal(empty.status,400);assert.equal(long.status,400);});
 it('retrieves and paginates message history only for members',async()=>{const history=await request(app).get(`/api/conversations/${conversationId}/messages?page=1&limit=1`).set('Authorization',`Bearer ${tokens[1]}`);const denied=await request(app).get(`/api/conversations/${conversationId}/messages`).set('Authorization',`Bearer ${tokens[2]}`);assert.equal(history.status,200,JSON.stringify(history.body));assert.equal(history.body.data.messages.length,1);assert.equal(history.body.data.pagination.page,1);assert.equal(history.body.data.pagination.limit,1);assert.equal(history.body.data.pagination.total,1);assert.equal(history.body.data.messages[0].id,firstMessageId);assert.equal(history.body.data.messages[0].messageType,'TEXT');assert.equal(history.body.data.messages[0].content,'hello from REST');assert.equal(history.body.data.messages[0].status,'SENT');assert.equal(denied.status,404);});
 it('rejects unauthorized REST message sends',async()=>{const result=await request(app).post(`/api/conversations/${conversationId}/messages`).set('Authorization',`Bearer ${tokens[2]}`).send({content:'intrusion'});assert.equal(result.status,404);});
 it('reports unread counts only to the recipient',async()=>{const recipient=await request(app).get('/api/conversations').set('Authorization',`Bearer ${tokens[1]}`);const item=recipient.body.data.find((value:{conversationId:string})=>value.conversationId===conversationId);assert.equal(item.unreadCount,1);});
 it('rejects marking a sender message as read by its sender',async()=>{const result=await request(app).post(`/api/conversations/${conversationId}/messages/${firstMessageId}/read`).set('Authorization',`Bearer ${tokens[0]}`);assert.equal(result.status,403);});
 it('accepts a recipient delivery acknowledgement and updates status',async()=>{const event=new Promise<{conversationId:string;messageId:string;status:string;deliveredAt:Date|null;recipientId:string}>(resolve=>sockets[0]!.once('message:delivered',resolve));const ack=await emitAck<{messageId:string;status:'DELIVERED'|'READ';deliveredAt:Date|null;readAt:Date|null}>(sockets[1]!,'message:delivered',{messageId:firstMessageId});assert.equal(ack.success,true);if(!ack.success)throw new Error('Delivery acknowledgement failed');assert.equal(ack.data.messageId,firstMessageId);assert.equal(ack.data.status,'DELIVERED');assert.ok(ack.data.deliveredAt);const receipt=await event;assert.deepEqual({conversationId:receipt.conversationId,messageId:receipt.messageId,status:receipt.status,recipientId:receipt.recipientId},{conversationId,messageId:firstMessageId,status:'DELIVERED',recipientId:ids[1]});assert.ok(receipt.deliveredAt);const history=await request(app).get(`/api/conversations/${conversationId}/messages`).set('Authorization',`Bearer ${tokens[0]}`);assert.equal(history.body.data.messages[0].status,'DELIVERED');});
 it('marks a recipient message read without duplicating an existing delivery event and rejects a non-member read',async()=>{let deliveryEvents=0;const onDelivery=()=>{deliveryEvents+=1;};sockets[0]!.on('message:delivered',onDelivery);const event=new Promise<{messageId:string;status:string}>(resolve=>sockets[0]!.once('message:read',resolve));const ack=await emitAck<{conversationId:string;messageId:string;status:'READ';readAt:Date|null}>(sockets[1]!,'message:read',{conversationId,messageId:firstMessageId});assert.equal(ack.success,true);if(!ack.success)throw new Error('Read acknowledgement failed');assert.equal(ack.data.messageId,firstMessageId);assert.equal(ack.data.status,'READ');assert.ok(ack.data.readAt);assert.equal((await event).status,'READ');assert.equal(deliveryEvents,0);sockets[0]!.off('message:delivered',onDelivery);const denied=await request(app).post(`/api/conversations/${conversationId}/messages/${firstMessageId}/read`).set('Authorization',`Bearer ${tokens[2]}`);assert.equal(denied.status,404);});
 it('records delivery and notifies the sender when read is acknowledged first with only a message ID',async()=>{const incoming=waitForMessage(sockets[1]!);const sent=await request(app).post(`/api/conversations/${conversationId}/messages`).set('Authorization',`Bearer ${tokens[0]}`).send({content:'read before delivery acknowledgement'});assert.equal(sent.status,201);const newMessage=await incoming;assert.equal(newMessage.id,sent.body.data.id);assert.equal(newMessage.status,'SENT');assert.equal(newMessage.deliveredAt,null);const events:string[]=[];const delivery=new Promise<{conversationId:string;messageId:string;status:string;deliveredAt:Date|null;recipientId:string}>(resolve=>sockets[0]!.once('message:delivered',value=>{events.push('message:delivered');resolve(value);}));const read=new Promise<{conversationId:string;messageId:string;status:string;readAt:Date|null;readerId:string}>(resolve=>sockets[0]!.once('message:read',value=>{events.push('message:read');resolve(value);}));const ack=await emitAck<{conversationId:string;messageId:string;status:'READ';readAt:Date|null}>(sockets[1]!,'message:read',{messageId:newMessage.id});assert.equal(ack.success,true);if(!ack.success)throw new Error('Read acknowledgement failed');assert.equal(ack.data.conversationId,conversationId);assert.equal(ack.data.messageId,newMessage.id);assert.equal(ack.data.status,'READ');assert.ok(ack.data.readAt);const[deliveryEvent,readEvent]=await Promise.all([delivery,read]);assert.deepEqual(events,['message:delivered','message:read']);assert.equal(deliveryEvent.conversationId,conversationId);assert.equal(deliveryEvent.messageId,newMessage.id);assert.equal(deliveryEvent.status,'DELIVERED');assert.equal(deliveryEvent.recipientId,ids[1]);assert.ok(deliveryEvent.deliveredAt);assert.equal(readEvent.messageId,newMessage.id);assert.equal(readEvent.status,'READ');assert.equal(readEvent.readerId,ids[1]);const[receipts]=await pool.execute<(import('mysql2').RowDataPacket&{delivered_at:Date|null;read_at:Date|null})[]>('SELECT delivered_at,read_at FROM message_receipts WHERE message_id=? AND user_id=?',[newMessage.id,ids[1]!]);assert.ok(receipts[0]?.delivered_at);assert.ok(receipts[0]?.read_at);assert.equal(new Date(receipts[0]!.delivered_at!).getTime(),new Date(deliveryEvent.deliveredAt!).getTime());let deliveryEvents=1;const onDelivery=()=>{deliveryEvents+=1;};sockets[0]!.on('message:delivered',onDelivery);const lateAck=await emitAck<{messageId:string;status:'DELIVERED'|'READ';deliveredAt:Date|null;readAt:Date|null}>(sockets[1]!,'message:delivered',{messageId:newMessage.id});assert.equal(lateAck.success,true);if(!lateAck.success)throw new Error('Late delivery acknowledgement failed');assert.equal(lateAck.data.status,'READ');assert.ok(lateAck.data.deliveredAt);assert.ok(lateAck.data.readAt);assert.equal(deliveryEvents,1);sockets[0]!.off('message:delivered',onDelivery);});
 it('rejects missing and invalid Socket.IO credentials',async()=>{await assert.rejects(connectSocket(),/Socket authentication required/);await assert.rejects(connectSocket('not-a-valid-jwt'),/Access token is invalid or expired/);});
 it('authorizes conversation rooms and rejects an outsider join',async()=>{const accepted=await emitAck<{conversationId:string}>(sockets[0]!,'conversation:join',{conversationId});const denied=await emitAck<{conversationId:string}>(sockets[2]!,'conversation:join',{conversationId});assert.equal(accepted.success,true);assert.equal(denied.success,false);});
 it('sends the current peer presence to a joining socket and authorizes typing events',async()=>{const left=await emitAck<{conversationId:string}>(sockets[0]!,'conversation:leave',{conversationId});assert.equal(left.success,true);const unjoinedTyping=await emitAck<{conversationId:string}>(sockets[0]!,'typing:start',{conversationId});assert.equal(unjoinedTyping.success,false);const presence=new Promise<{userId:string;isOnline:boolean;lastSeen:Date|null}>(resolve=>sockets[0]!.once('presence:update',resolve));const joined=await emitAck<{conversationId:string}>(sockets[0]!,'conversation:join',{conversationId});assert.equal(joined.success,true);const peer=await presence;assert.equal(peer.userId,ids[1]);assert.equal(peer.isOnline,true);assert.ok(peer.lastSeen);const start=new Promise<{conversationId:string;userId:string}>(resolve=>sockets[1]!.once('typing:start',resolve));const started=await emitAck<{conversationId:string}>(sockets[0]!,'typing:start',{conversationId});assert.equal(started.success,true);assert.deepEqual(await start,{conversationId,userId:ids[0]});const stop=new Promise<{conversationId:string;userId:string}>(resolve=>sockets[1]!.once('typing:stop',resolve));const stopped=await emitAck<{conversationId:string}>(sockets[0]!,'typing:stop',{conversationId});assert.equal(stopped.success,true);assert.deepEqual(await stop,{conversationId,userId:ids[0]});const outsider=await emitAck<{conversationId:string}>(sockets[2]!,'typing:start',{conversationId});assert.equal(outsider.success,false);});
 it('sends socket messages only after persistence and enforces sender membership',async()=>{const incoming=new Promise<{message:MessageDto;persistedCount:number}>(resolve=>sockets[1]!.once('message:new',async message=>{const[rows]=await pool.execute<(import('mysql2').RowDataPacket&{total:number})[]>('SELECT COUNT(*) AS total FROM messages WHERE id=?',[message.id]);resolve({message,persistedCount:Number(rows[0]?.total??0)});}));const sent=await emitAck<MessageDto>(sockets[0]!,'message:send',{conversationId,content:'hello over socket'});assert.equal(sent.success,true);if(!sent.success)throw new Error('Socket message send failed');socketMessageId=sent.data.id;const delivery=await incoming;assert.equal(delivery.message.id,socketMessageId);assert.equal(delivery.message.content,'hello over socket');assert.equal(delivery.persistedCount,1);const denied=await emitAck<MessageDto>(sockets[2]!,'message:send',{conversationId,content:'unauthorized'});assert.equal(denied.success,false);const[rows]=await pool.execute<(import('mysql2').RowDataPacket&{total:number})[]>('SELECT COUNT(*) AS total FROM messages WHERE id=?',[socketMessageId]);assert.equal(Number(rows[0]?.total),1);});
 it('validates and sends JPEG, PNG, and WebP image messages after persistence',async()=>{for(const format of ['jpeg','png','webp'] as const){const image=await sharp({create:{width:2,height:3,channels:3,background:'#0088cc'}}).toFormat(format).toBuffer();const incoming=waitForMessage(sockets[1]!);const sent=await request(app).post(`/api/conversations/${conversationId}/messages/image`).set('Authorization',`Bearer ${tokens[0]}`).attach('image',image,{filename:`fixture.${format==='jpeg'?'jpg':format}`,contentType:`image/${format}`});assert.equal(sent.status,201,JSON.stringify(sent.body));assert.equal(sent.body.data.messageType,'IMAGE');assert.equal(sent.body.data.image.width,2);assert.equal((await incoming).id,sent.body.data.id);const[metadata]=await pool.execute<(import('mysql2').RowDataPacket&{storage_key:string;mime_type:string})[]>('SELECT u.storage_key,u.mime_type FROM uploads u WHERE u.id=?',[sent.body.data.image.id]);assert.ok(metadata[0]?.storage_key.startsWith(sent.body.data.image.id));const imageResponse=await request(app).get(sent.body.data.image.url).set('Authorization',`Bearer ${tokens[1]}`);assert.equal(imageResponse.status,200);assert.match(String(imageResponse.headers['content-type']),/^image\//);const outsider=await request(app).get(sent.body.data.image.url).set('Authorization',`Bearer ${tokens[2]}`);assert.equal(outsider.status,404);}
  const history=await request(app).get(`/api/conversations/${conversationId}/messages?page=1&limit=20`).set('Authorization',`Bearer ${tokens[1]}`);assert.ok(history.body.data.messages.filter((message:{messageType:string})=>message.messageType==='IMAGE').length>=3);
  const stagedImage=await sharp({create:{width:4,height:5,channels:3,background:'#ffcc00'}}).png().toBuffer();const staged=await request(app).post('/api/uploads/images').set('Authorization',`Bearer ${tokens[0]}`).attach('image',stagedImage,{filename:'staged.png',contentType:'image/png'});assert.equal(staged.status,201);const received=waitForMessage(sockets[1]!);const sent=await request(app).post(`/api/conversations/${conversationId}/messages/image`).set('Authorization',`Bearer ${tokens[0]}`).send({imageId:staged.body.data.id});assert.equal(sent.status,201);assert.equal((await received).id,sent.body.data.id);
 });
 it('rejects unauthorized image sends before accepting the multipart body',async()=>{const image=await sharp({create:{width:1,height:1,channels:3,background:'#ffffff'}}).png().toBuffer();const result=await request(app).post(`/api/conversations/${conversationId}/messages/image`).set('Authorization',`Bearer ${tokens[2]}`).attach('image',image,{filename:'private.png',contentType:'image/png'});assert.equal(result.status,404);});
 it('rejects unsupported, spoofed and oversized images',async()=>{const svg=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>');const unsupported=await request(app).post('/api/uploads/images').set('Authorization',`Bearer ${tokens[0]}`).attach('image',svg,{filename:'vector.svg',contentType:'image/svg+xml'});assert.equal(unsupported.status,400);const spoofed=await request(app).post('/api/uploads/images').set('Authorization',`Bearer ${tokens[0]}`).attach('image',svg,{filename:'photo.png',contentType:'image/png'});assert.equal(spoofed.status,415);const large=Buffer.alloc(10*1024*1024+1);const oversized=await request(app).post('/api/uploads/images').set('Authorization',`Bearer ${tokens[0]}`).attach('image',large,{filename:'large.jpg',contentType:'image/jpeg'});assert.equal(oversized.status,413);});
 it('marks a user offline only after the final socket disconnects and publishes last seen',async()=>{const offline=waitForPresence(sockets[1]!,ids[0]!,false);sockets[0]!.disconnect();const event=await offline;assert.ok(event.lastSeen);const[rows]=await pool.execute<(import('mysql2').RowDataPacket&{last_seen:Date|null})[]>('SELECT last_seen FROM users WHERE id=?',[ids[0]!]);assert.ok(rows[0]?.last_seen);});
});
