import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import { rateLimit } from 'express-rate-limit';
import { env } from './config/env';
import { checkDatabase } from './config/database';
import { authRouter } from './routes/auth.routes';
import { usersRouter } from './routes/users.routes';
import { conversationsRouter } from './routes/conversations.routes';
import { uploadsRouter } from './routes/uploads.routes';
import { asyncHandler } from './utils/async-handler';
import { success } from './utils/response';
import { HttpError } from './utils/http-error';
import { errorHandler } from './middleware/error-handler';

export const app=express();
app.disable('x-powered-by');
app.set('trust proxy',1);
app.use(helmet());
app.use(cors({origin:env.CORS_ORIGIN.split(',').map(s=>s.trim()),credentials:true}));
app.use(express.json({limit:'32kb'}));
app.use(cookieParser());
app.use(rateLimit({windowMs:15*60*1000,limit:300,standardHeaders:true,legacyHeaders:false}));
app.get('/api/health',asyncHandler(async(_req,res)=>{const ok=await checkDatabase();res.status(ok?200:503).json({success:ok,data:{server:'ok',database:ok?'ok':'unavailable'},message:ok?'Success':'Database unavailable'});}));
const authLimiter=rateLimit({windowMs:15*60*1000,limit:10,standardHeaders:true,legacyHeaders:false,message:{success:false,message:'Too many authentication attempts',code:'RATE_LIMITED'}});
app.use('/api/auth',authLimiter,authRouter);
app.use('/api/users',usersRouter);
app.use('/api/conversations',conversationsRouter);
app.use('/api/uploads',uploadsRouter);
app.use((_req,_res,next)=>next(new HttpError(404,'NOT_FOUND','Route not found')));
app.use(errorHandler);

